name: build and deploy docker image using github actions

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: push image to docker hub
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: rakesh9711/app:latest